import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";
import "./clerk.css";

export const metadata: Metadata = {
  title: "Flowble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className="antialiased font-dmSans">
          <div vaul-drawer-wrapper="">{children}</div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
